### ISSUE TITLE
Migrate off BuildKite

### ISSUE THREAD

**Issue by benbz** [matrix-org/matrix-is-tester#23]
We're ramping down our BuildKite usage and this project is one of the few left on it. How much work would it be to migrate to GH Actions/similar so that CI was under your span of control?

**Comment by DMRobertson** [comment]
Should be easy to translate https://github.com/matrix-org/matrix-is-tester/blob/main/.buildkite/pipeline.yml to GHA.

**Comment by DMRobertson** [comment]
That's completely fine.

**Comment by DMRobertson** [comment]
@benbz this should be done. I don't think I can delete the repo/project from buildkite. Is there anything else you need us to do for this repo?

**Comment by benbz** [comment]
I can tidy up the BK/pipelines part. TYVM
